import type { User, Asset, Incident, Maintenance } from '@/lib/types';
import { subDays, format } from 'date-fns';

export const users: User[] = [
  {
    id: 'admin',
    name: 'Alex Johnson',
    role: 'Operations Manager',
    avatar: 'user1',
    accessKey: 'password123',
    status: 'On-Duty',
  },
  {
    id: 'tech',
    name: 'Maria Garcia',
    role: 'Technician',
    avatar: 'user2',
    accessKey: 'password123',
    status: 'On-Duty',
  },
  {
    id: 'user3',
    name: 'Kenji Tanaka',
    role: 'Technician',
    avatar: 'user3',
    accessKey: 'password123',
    status: 'On-Call',
  },
  {
    id: 'user4',
    name: 'Emily White',
    role: 'Technician',
    avatar: 'user4',
    accessKey: 'password123',
    status: 'Off-Duty',
  },
];

export const assets: Asset[] = [
  {
    id: 'E-001',
    name: 'Main Lobby Elevator',
    type: 'Elevator',
    location: 'Tower A, Lobby',
    status: 'Operational',
    installDate: '2020-01-15',
    lastMaintenance: format(subDays(new Date(), 30), 'yyyy-MM-dd'),
    nextMaintenance: format(subDays(new Date(), -150), 'yyyy-MM-dd'),
    uptime: 99.8,
  },
  {
    id: 'E-002',
    name: 'Service Elevator 1',
    type: 'Elevator',
    location: 'Tower B, Basement',
    status: 'Fault',
    installDate: '2021-03-20',
    lastMaintenance: format(subDays(new Date(), 90), 'yyyy-MM-dd'),
    nextMaintenance: format(subDays(new Date(), -90), 'yyyy-MM-dd'),
    uptime: 95.2,
  },
  {
    id: 'S-001',
    name: 'Central Atrium Escalator',
    type: 'Escalator',
    location: 'Central Atrium',
    status: 'Warning',
    installDate: '2019-08-01',
    lastMaintenance: format(subDays(new Date(), 15), 'yyyy-MM-dd'),
    nextMaintenance: format(subDays(new Date(), -45), 'yyyy-MM-dd'),
    uptime: 98.5,
  },
  {
    id: 'E-003',
    name: 'Parking Garage Lift',
    type: 'Elevator',
    location: 'Parking P3',
    status: 'Operational',
    installDate: '2022-05-10',
    lastMaintenance: format(subDays(new Date(), 60), 'yyyy-MM-dd'),
    nextMaintenance: format(subDays(new Date(), -120), 'yyyy-MM-dd'),
    uptime: 99.9,
  },
];

export const incidents: Incident[] = [
  {
    id: 'INC-001',
    title: 'Unresponsive Call Button',
    assetId: 'S-001',
    status: 'Pending',
    priority: 'High',
    reportedBy: 'admin',
    reportedAt: format(subDays(new Date(), 1), 'yyyy-MM-dd HH:mm'),
    description: 'The "up" call button for the Central Atrium Escalator is not responding when pressed. The escalator itself is running, but users cannot initiate movement from a standstill. Visual inspection shows no obvious damage to the button panel.',
  },
  {
    id: 'INC-002',
    title: 'Door Obstruction Sensor Fault',
    assetId: 'E-002',
    status: 'In Progress',
    priority: 'Critical',
    reportedBy: 'tech',
    reportedAt: format(subDays(new Date(), 0), 'yyyy-MM-dd HH:mm'),
    description: 'Service Elevator 1 doors are failing to close, citing an obstruction even when the path is clear. Manual override is required for operation. This is causing significant delays in service transport. The sensor alignment may be off or the sensor itself may have failed.',
  },
  {
    id: 'INC-003',
    title: 'Loud Grinding Noise',
    assetId: 'E-001',
    status: 'Resolved',
    priority: 'Medium',
    reportedBy: 'user3',
    reportedAt: format(subDays(new Date(), 5), 'yyyy-MM-dd HH:mm'),
    description: 'Main Lobby Elevator is making a loud grinding noise during ascent between floors 10 and 15. The noise is intermittent but concerning to passengers.',
    resolutionNotes: 'Technician investigated and found a loose guide rail bolt. Tightened bolt to spec, tested operation. Noise is resolved.',
    resolvedAt: format(subDays(new Date(), 4), 'yyyy-MM-dd HH:mm'),
  },
  {
    id: 'INC-004',
    title: 'Sudden Stop between floors',
    assetId: 'E-002',
    status: 'Unresolved',
    priority: 'Critical',
    reportedBy: 'admin',
    reportedAt: format(subDays(new Date(), 10), 'yyyy-MM-dd HH:mm'),
    description: 'Service Elevator 1 performed an emergency stop between floors 3 and 4 with no warning. The car had to be manually reset. This is the second time this has occurred in a month. Possible issue with the drive controller or power supply unit.',
  },
];

export const maintenanceSchedule: Maintenance[] = [
  {
    id: 'M-001',
    assetId: 'E-001',
    scheduledDate: format(subDays(new Date(), -30), 'yyyy-MM-dd'),
    type: 'Routine Check',
    status: 'Scheduled',
  },
  {
    id: 'M-002',
    assetId: 'S-001',
    scheduledDate: format(subDays(new Date(), -10), 'yyyy-MM-dd'),
    type: 'Repair',
    status: 'Scheduled',
  },
    {
    id: 'M-003',
    assetId: 'E-002',
    scheduledDate: format(subDays(new Date(), 2), 'yyyy-MM-dd'),
    type: 'Upgrade',
    status: 'In Progress',
  },
  {
    id: 'M-004',
    assetId: 'E-003',
    scheduledDate: format(subDays(new Date(), -45), 'yyyy-MM-dd'),
    type: 'Routine Check',
    status: 'Scheduled',
  },
];
